version: '3'

networks :
    net :
        name : myinception_net
        driver : bridge

volumes :
    maria_database :
        driver : local
        driver_opts :
            type : none # dont use NFS (Network File System) or tmpfs (temporary file system) for this volume
            o : bind # this is the option to bind the volume to a specific path on the host machine
            device : /home/ildaboun/data/mariadb # the path on the host machine where the volume will be mounted

    wordpress_database :
        driver : local
        driver_opts :
          type : none
          o : bind
          device : /home/ildaboun/data/wordpress
secrets:
    MYSQL_PASSWORD :
        file : ../secrets/MYSQL_PASSWORD.txt
    MYSQL_ROOT_PASSWORD :
        file : ../secrets/MYSQL_ROOT_PASSWORD.txt
    WP_ADMIN_PASSWORD :
        file : ../secrets/WP_ADMIN_PASSWORD.txt
    WP_USER_PASSWORD :
        file : ../secrets/WP_USER_PASSWORD.txt
    FTP_PASSWORD :
        file : ../secrets/FTP_PASSWORD.txt





services :
    mariadb :
        container_name : mariadb
        build : ./requirements/mariadb # the dockerfile located inside ./mariadb
        image : mariadb
        restart : on-failure
        env_file :
            - .env
        secrets :
            - MYSQL_PASSWORD
            - MYSQL_ROOT_PASSWORD
        expose :
            - "3306"
        volumes :
            - maria_database:/var/lib/mysql
        networks :
            - net

    wordpress :
        container_name : wordpress
        build : ./requirements/wordpress
        image : wordpress
        restart : on-failure
        env_file :
            - .env
        secrets :
            - WP_ADMIN_PASSWORD
            - WP_USER_PASSWORD
            - MYSQL_PASSWORD
        expose :
            - "9000"
        volumes :
          - wordpress_database:/var/www/wordpress
        networks :
          - net
        depends_on :
            - mariadb
            - redis

    nginx :
      container_name : nginx
      build : ./requirements/nginx
      image : nginx
      restart : on-failure
      ports :
          - "443:443"
      networks :
          - net
      volumes :
        - wordpress_database:/var/www/wordpress # named volume
      depends_on :
          - mariadb
          - wordpress
    adminer :
        container_name : adminer
        build : ./requirements/adminer
        image : adminer
        restart : on-failure
        expose :
            - "9000" # it okeey if we used the same port as wordpress, because they are in different containers
        networks :
            - net
    resume :
        container_name : resume
        build : ./requirements/resume
        image : resume
        restart : on-failure
        expose :
            - "3000"
        networks :
            - net

    redis :
        container_name : redis
        build : ./requirements/redis
        image : redis
        restart : on-failure
        expose :
            - "6379"
        networks:
            - net

    ftp :
        container_name : ftp
        build : ./requirements/ftp
        image : ftp
        restart : on-failure
        secrets :
            - FTP_PASSWORD
        networks:
            - net
        volumes :
            - wordpress_database:/var/www/wordpress
        ports :
            - "21:21"
            - "40000-40005:40000-40005"
        depends_on :
            - wordpress
        env_file :
            - .env
    cadvisor :
        container_name : cadvisor
        build : ./requirements/cadvisor
        image : cadvisor
        restart : on-failure
        expose :
            -  "8080"
        volumes :
            - /var/run:/var/run:ro # ask docker.sock for the container X name, the docker.sock memmory isnt fixed that why we bind the whole /var directory
            - /sys:/sys:ro # resource usage
            - /:/rootfs:ro # check the total size
            - /var/lib/docker:/var/lib/docker:ro # track overlayfs
            - /dev/disk/:/dev/disk:ro
        networks :
            - net















