version: '3'

networks :
    net :
        name : myinception_net
        driver : bridge

volumes :
    maria_database :
        driver : local
        driver_opts :
            type : none # dont use NFS (Network File System) or tmpfs (temporary file system) for this volume
            o : bind # this is the option to bind the volume to a specific path on the host machine
            device : /home/ildaboun/data/mariadb # the path on the host machine where the volume will be mounted

    wordpress_database :
        driver : local
        driver_opts :
          type : none
          o : bind
          device : /home/ildaboun/data/wordpress
secrets:
    MYSQL_PASSWORD :
        file : ./secrets/MYSQL_PASSWORD.txt
    MYSQL_ROOT_PASSWORD :
        file : ./secrets/MYSQL_ROOT_PASSWORD.txt
    WP_ADMIN_PASSWORD :
        file : ./secrets/WP_ADMIN_PASSWORD.txt
    WP_USER_PASSWORD :
        file : ./secrets/WP_USER_PASSWORD.txt

    



services :
    mariadb :
        container_name : mariadb
        build : ./requirements/mariadb # the dockerfile located inside ./mariadb
        restart : always
        env_file :
            - .env
        secrets :
            - MYSQL_PASSWORD
            - MYSQL_ROOT_PASSWORD
        expose :
            - "3306"
        volumes :
            - maria_database:/var/lib/mysql
        networks :
            - net
  
    wordpress :
        container_name : wordpress
        build : ./requirements/wordpress
        restart : always
        env_file :
            - .env
        secrets :
            - WP_ADMIN_PASSWORD
            - WP_USER_PASSWORD
        expose :
            - "9000"
        volumes :
          - wordpress_database:/var/www/wordpress
        networks :
          - net
        depends_on :
            - mariadb
            - redis
    
    nginx :
      container_name : nginx
      build : ./requirements/nginx
      restart : always
      ports :
          - "443:443"
      networks :
          - net
      volumes :
        - wordpress_database:/var/www/wordpress
      depends_on :
          - mariadb
          - wordpress
    adminer :
        container_name : adminer
        build : ./requirements/adminer
        restart : always
        expose :
            - "9000" # it okeey if we used the same port as wordpress, because they are in different containers
        networks :
            - net
    resume : 
        container_name : resume
        build : ./requirements/resume
        restart : always
        expose :
            - "3000"
        networks :
            - net
    
    redis :
        container_name : redis
        build : ./requirements/redis
        restart : always
        expose :  
            - "6379"
        networks:
            - net
      



