version: '3'

networks:
  inception_network:
    driver: bridge
    name: inception_network

volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      device: ${DATA_PATH}/mariadb
      o: bind
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      device: ${DATA_PATH}/wordpress
      o: bind