server
{
    listen 443 ssl;
    listen [::]:443 ssl;
    server_name ildaboun.42.fr;
    ssl_certificate /etc/nginx/ssl/nginx.crt;
    ssl_certificate_key /etc/nginx/ssl/nginx.key;
    ssl_protocols TLSv1.2 TLSv1.3;
    root /var/www/wordpress;
    index index.php index.html index.htm;
    location ~ \.php$ # the $ to make sure the file end with .php and the ~ just to make sure its case sensitive
    {
        include snippets/fastcgi-php.conf;
        try_files $fastcgi_script_name =404;
        fastcgi_pass wordpress:9000;
    }
    # mind in alpine os the snippets directory isnt there
    #                      |
    # that what we include v
    
    #fastcgi_split_path_info ^(.+\.php)(/.+)$;
    #fastcgi_pass wordpress:9000;
    #fastcgi_index index.php; if the request is a directory nginx use index.php by default.
    #include fastcgi_params;
    #fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    #fastcgi_param PATH_INFO $fastcgi_path_info;

}