events
{

}

http
{
    include /etc/nginx/mime.types; #By writing include /etc/nginx/mime.types;, you ensure NGINX labels every single file correctly before throwing it over the network to the user!

server
{
    listen 443 ssl;
    listen [::]:443 ssl;
    server_name ildaboun.42.fr;
    ssl_certificate /etc/nginx/ssl/nginx.crt;
    ssl_certificate_key /etc/nginx/ssl/nginx.key;
    ssl_protocols TLSv1.2 TLSv1.3;

    root /var/www/wordpress;
    index index.php index.html index.htm;

    location /
    {
        try_files $uri $uri/ /index.php?$args; # if $uri and $uri/ failed we swich to index.php with the ?$args which the query string
    }

    location ~ ^/adminer # if the request start with /adminer we will execute this location block .
    {
        # mind that nginx only serve static files, so here all we forward the request to php-fpm,
        # and php-fpm will handle the request and return the response to nginx, and nginx will return the response to the client.
        root /var/www/html;
        include fastcgi_params;
        fastcgi_pass adminer:9000;
        fastcgi_param SCRIPT_FILENAME $document_root/index.php; # we hardcoded the path to index.php because adminer is a single file php application and why we get rid of script_name because we want to make sure that the request is always index.php and not any other file.
    }

    location /resume # when using regex nginx cant modify the request url
    {
        proxy_pass http://resume:3000/resume.html; # we forward the request as http and not as https because containers are on a safe network and we dont need to encrypt the traffic between containers.
    }

    location ~ \.php$ # the $ to make sure the file end with .php and the ~ just to make sure its case sensitive
    {
        #include snippets/fastcgi-php.conf;
        include fastcgi_params;
        try_files $uri =404;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_pass wordpress:9000;
    }
    # mind in alpine os the snippets directory isnt there
    #                      |
    # that what we include v

    #fastcgi_split_path_info ^(.+\.php)(/.+)$;
    #fastcgi_pass wordpress:9000;
    #fastcgi_index index.php; if the request is a directory nginx use index.php by default.
    #include fastcgi_params;
    #fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    #fastcgi_param PATH_INFO $fastcgi_path_info;
}
}